---
title: "Supplementary Materials for 'XyZ'"
author: "Hornsey and colleagues (2024)"
date: "2024-01-08"
output: html_document
---

```{r ech=FALSE, include=FALSE}
library(tidyverse)
library(metaumbrella)
dat_sleep = readxl::read_excel("combined DISCA UR extraction spreadsheet_28-02-2024.xlsx",
                             sheet = 1) %>%
  filter(!is.na(author) & is.na(Discard))

dat_sleep$factor = dat_sleep$Factor
dat_sleep = subset(dat_sleep, select=-c(Factor))
colnames(dat_sleep)[2] <- "Pop"
colnames(dat_sleep)[which(colnames(dat_sleep) == "O - subjective or objective for new factor")] <- "Type_outcome"
colnames(dat_sleep)[which(colnames(dat_sleep) == "P - for new factor")] <- "Population"
colnames(dat_sleep)[which(colnames(dat_sleep) == "I - for new factor")] <- "Intervention"
colnames(dat_sleep)[which(colnames(dat_sleep) == "O - for new factor")] <- "Outcome"
# dat_sleep$Outcome = paste0(dat_sleep$Outcome, "_", dat_sleep$Type_outcome)


dat_fact = dat_sleep %>%
  group_by(factor) %>%
  slice(1)

dat_fact_rest = dat_fact %>%
  select(factor, Population, Intervention, Outcome, Type_outcome)
```

```{r}
dat_errors = metaumbrella::view.errors.umbrella(dat_sleep)
```

```{r}
res = umbrella(dat_sleep, mult.level=TRUE,
               verbose = FALSE)

DT::datatable(summary(res), 
              rownames = FALSE,
              options = list(  # options
                scrollX = TRUE,
                dom = c('ft'), 
                scrollY = "600px", 
                pageLength = 600,
                autoWidth = TRUE,
                columnDefs = list(
                  list(width = '110px',
                       targets = "_all"),
                  list(className = 'dt-center', 
                       targets = "_all"))))

```

```{r}
evid = add.evidence(res, criteria="GRADE")

DT::datatable(summary(evid), 
              rownames = FALSE,
              options = list(  # options
                scrollX = TRUE,
                dom = c('ft'), 
                scrollY = "600px", 
                pageLength = 600,
                autoWidth = TRUE,
                columnDefs = list(
                  list(width = '110px',
                       targets = "_all"),
                  list(className = 'dt-center', 
                       targets = "_all"))))

```

# Forest (objective)
```{r, fig.width=12, fig.height=10}
sum_evid = summary(evid)
 
sum_evid$I2 = as.numeric(sum_evid$I2)
sum_evid$factor = sum_evid$Factor
dat_plot = left_join(sum_evid, dat_fact_rest)

dat_plot$Population = substr(dat_plot$Population, 1, 20) 
dat_plot$Intervention = substr(dat_plot$Intervention, 1, 20) 
dat_plot$Outcome = substr(dat_plot$Outcome, 1, 20) 
dat_plot$Factor = substr(dat_plot$Factor, 1, 30)
dat_plot = dat_plot[order(dat_plot$Population),]
dat_plot = dat_plot %>% filter(n_studies > 1)
forest(dat_plot %>% filter(grepl("Objective", Type_outcome, fixed=TRUE)),
       layout = "RevMan5",
       subgroup = "Intervention",
       subgroup.name = "Intervention",
      leftcols = c("Population", 
                   "Outcome", "n_studies", "total_n", "I2", "Class",
                   "effect.ci"),
       leftlabs = c("Population", 
                    "Outcome", "n-studies", "n-sample", "I2", "Class",
                    "eSMD + 95% CI")
)

```


# Forest (Subjective)
```{r, fig.width=12, fig.height=15}
forest(dat_plot %>% filter(grepl("Subjective", Type_outcome, fixed=TRUE)),
       layout = "RevMan5",
       subgroup = "Intervention",
       subgroup.name = "Intervention",
       order = "Class",
      leftcols = c("Population", 
                   "Outcome", "n_studies", "total_n", "I2", "Class",
                   "effect.ci"),
       leftlabs = c("Population", 
                    "Outcome", "n-studies", "n-sample", "I2", "Class",
                    "eSMD + 95% CI")
)

```

```{r, eval=FALSE}
downloadthis::download_this(
  dat_errors,
  output_name = "errors",
  output_extension = ".xlsx",
  button_label = "Download error/warninga",
  button_type = "warning",
  has_icon = TRUE,
  icon = "fa fa-save"
)
```
