---
title: "Supplementary Materials for 'XyZ'"
author: "Hornsey and colleagues (2024)"
date: "2024-01-08"
output: html_document
---

```{r ech=FALSE, include=FALSE}
library(tidyverse)
library(metaumbrella)
dat_sleep = readxl::read_excel("combined DISCA UR extraction spreadsheet_18-01-2024 (2).xlsx",
                             sheet = 1) %>%
  filter(!is.na(author))

dat_fact = dat_sleep %>%
  group_by(factor) %>%
  slice(1) 

colnames(dat_fact)[c(2, 6, 8)] <- c("Population", "Intervention", "Outcome")
dat_fact = dat_fact %>%
  select(factor, Population, Intervention, Outcome)

```

```{r}
dat_errors = metaumbrella::view.errors.umbrella(dat_sleep)
```

```{r}
res = umbrella(dat_sleep, mult.level=TRUE,
               verbose = FALSE)

DT::datatable(summary(res), 
              rownames = FALSE,
              options = list(  # options
                scrollX = TRUE,
                dom = c('ft'), 
                scrollY = "600px", 
                pageLength = 600,
                autoWidth = TRUE,
                columnDefs = list(
                  list(width = '110px',
                       targets = "_all"),
                  list(className = 'dt-center', 
                       targets = "_all"))))

```

```{r}
evid = add.evidence(res, criteria="GRADE")

DT::datatable(summary(evid), 
              rownames = FALSE,
              options = list(  # options
                scrollX = TRUE,
                dom = c('ft'), 
                scrollY = "600px", 
                pageLength = 600,
                autoWidth = TRUE,
                columnDefs = list(
                  list(width = '110px',
                       targets = "_all"),
                  list(className = 'dt-center', 
                       targets = "_all"))))

```


```{r}
sum_evid = summary(evid)
 
sum_evid$I2 = as.numeric(sum_evid$I2)
sum_evid$factor = sum_evid$Factor
dat_plot = left_join(sum_evid, dat_fact)
dat_plot$Factor = substr(dat_plot$Factor, 1, 20)  
forest(dat_plot,
       layout = "RevMan5",
       subgroup = "Class",
       subgroup.name = "Class",
      leftcols = c("Population", "Intervention", "Outcome", "Class", "n_studies", "total_n",  "effect.ci"),
       leftlabs = c("Population", "Intervention", "Outcome", "Class", "n-studies", "n-sample", 
                    "eSMD + 95% CI"),
)

```

```{r, echo=FALSE}
downloadthis::download_this(
  dat_errors,
  output_name = "errors",
  output_extension = ".xlsx",
  button_label = "Download error/warninga",
  button_type = "warning",
  has_icon = TRUE,
  icon = "fa fa-save"
)
```
